const express=require('express');const fs=require('fs');const path=require('path');
const app=express();app.use(express.json());
const PORT=process.env.PORT||3000, ROOT=__dirname, dbFile=path.join(ROOT,'data/db.json');
let catalog=require('./data/catalog.json');let db={orders:[],users:[],messages:[],overrides:{},favorites:{}};try{db={...db,...JSON.parse(fs.readFileSync(dbFile))}}catch(e){}
const save=()=>fs.writeFileSync(dbFile,JSON.stringify(db,null,2));
const adminIds=(process.env.ADMIN_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);
function user(req){let u=req.body?.user||req.query.user||{};let id=String(u.id||req.headers['x-telegram-user']||'preview');if(!db.users.find(x=>x.id===id)){db.users.push({id,name:u.first_name||'Гость',username:u.username||'',createdAt:Date.now()});save()}return{id,name:u.first_name||'Гость'} }
function products(){return catalog.map(x=>({...x,price:db.overrides[x.id]?.price??x.price,hidden:db.overrides[x.id]?.hidden||false,stock:db.overrides[x.id]?.stock??x.stock})).filter(x=>!x.hidden)}
app.use(express.static(path.join(ROOT,'webapp')));
app.get('/api/catalog',(req,res)=>res.json(products()));
app.get('/api/me',(req,res)=>{let u=user(req);res.json({user:u,orders:db.orders.filter(o=>o.userId===u.id),favorites:db.favorites[u.id]||[]})});
app.post('/api/favorite',(req,res)=>{let u=user(req),id=req.body.id;db.favorites[u.id]=db.favorites[u.id]||[];let a=db.favorites[u.id],i=a.indexOf(id);i<0?a.push(id):a.splice(i,1);save();res.json(a)});
app.post('/api/orders',(req,res)=>{let u=user(req),b=req.body,items=(b.items||[]).map(i=>{let p=products().find(x=>x.id===i.id);return p&&{...p,qty:i.qty}}).filter(Boolean),subtotal=items.reduce((s,i)=>s+i.price*i.qty,0),delivery=b.delivery==='pickup'?0:subtotal>=10000?0:490;let o={id:'CE-'+String(Date.now()).slice(-7),userId:u.id,user:u,items,subtotal,delivery,total:subtotal+delivery,status:'Новый',payment:b.payment||'card',contact:b.contact||{},createdAt:Date.now()};db.orders.unshift(o);save();res.json({order:o,paymentUrl:process.env.YUKASSA_SHOP_ID?'#yookassa-not-configured':null})});
app.get('/api/orders',(req,res)=>{let u=user(req);res.json(db.orders.filter(o=>o.userId===u.id))});
app.post('/api/orders/:id/cancel',(req,res)=>{let o=db.orders.find(x=>x.id===req.params.id);if(o&&['Новый','Ожидает оплаты'].includes(o.status)){o.status='Отменён';save()}res.json(o||{})});
app.post('/api/support',(req,res)=>{let u=user(req),m={id:Date.now(),userId:u.id,name:u.name,text:req.body.text,createdAt:Date.now(),from:'user'};db.messages.push(m);save();notifyAdmins(m);res.json(m)});
app.get('/api/support',(req,res)=>{let u=user(req);res.json(db.messages.filter(m=>m.userId===u.id))});
app.get('/invoice/:id',(req,res)=>{let o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).send('Счёт не найден');res.send(invoice(o))});
function invoice(o){return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Счёт ${o.id}</title><style>body{font:14px Arial;max-width:800px;margin:40px auto;color:#111}h1{text-align:center;font-size:24px}.top{display:flex;justify-content:space-between;margin:40px 0}table{width:100%;border-collapse:collapse}td,th{border:1px solid #aaa;padding:10px;text-align:left}.sum{text-align:right;font-size:18px;margin-top:20px}@media print{button{display:none}}</style></head><body><button onclick="print()">Печать</button><h1>СЧЁТ НА ОПЛАТУ № ${o.id}</h1><div class="top"><div><b>Поставщик</b><br>Cocktail Embassy<br>Магазин барного стекла</div><div><b>Покупатель</b><br>${o.contact.company||o.user.name}<br>ИНН ${o.contact.inn||'—'} / КПП ${o.contact.kpp||'—'}<br>${o.contact.email||''}</div></div><table><tr><th>№</th><th>Наименование</th><th>Кол-во</th><th>Цена</th><th>Сумма</th></tr>${o.items.map((i,n)=>`<tr><td>${n+1}</td><td>${i.name}</td><td>${i.qty}</td><td>${i.price.toLocaleString('ru-RU')} ₽</td><td>${(i.price*i.qty).toLocaleString('ru-RU')} ₽</td></tr>`).join('')}</table><div class="sum">Итого к оплате: <b>${o.total.toLocaleString('ru-RU')} ₽</b></div><p>Без НДС. Счёт действителен в течение 5 рабочих дней.</p></body></html>`}
function notifyAdmins(m){if(!process.env.BOT_TOKEN)return;for(const id of adminIds)bot?.api.sendMessage(id,`💬 Поддержка от ${m.name}:\n${m.text}`).catch(()=>{})}
let bot=null; if(process.env.BOT_TOKEN){const {Bot,InlineKeyboard}=require('grammy');bot=new Bot(process.env.BOT_TOKEN);bot.command('start',ctx=>ctx.reply('🍸 Cocktail Embassy\nМагазин барного стекла', {reply_markup:{inline_keyboard:[[{text:'Открыть магазин',web_app:{url:(process.env.PUBLIC_URL||'')+'/'} }],[{text:'Каталог',callback_data:'catalog'}]]}}));bot.command('catalog',ctx=>ctx.reply('Каталог Cocktail Embassy\nОткройте витрину, чтобы выбрать бокалы.',{reply_markup:{inline_keyboard:[[{text:'Перейти в каталог',web_app:{url:(process.env.PUBLIC_URL||'')+'/#catalog'}}]]}}));bot.command('admin',ctx=>{if(!adminIds.includes(String(ctx.from.id)))return ctx.reply('⛔ Доступ запрещён');ctx.reply(`⚙️ Админ-панель\nЗаказов: ${db.orders.length}\nПользователей: ${db.users.length}\nВыручка: ${db.orders.filter(o=>o.status!=='Отменён').reduce((s,o)=>s+o.total,0).toLocaleString('ru-RU')} ₽`,{reply_markup:{inline_keyboard:[[{text:'📦 Заказы',callback_data:'orders'}],[{text:'📊 Статистика',callback_data:'stats'}]]}})});bot.callbackQuery('orders',ctx=>ctx.answerCallbackQuery().then(()=>ctx.reply(db.orders.slice(0,10).map(o=>`${o.id} · ${o.total} ₽ · ${o.status}`).join('\n')||'Заказов пока нет')));bot.start().catch(console.error)}
app.listen(PORT,'0.0.0.0',()=>console.log(`Cocktail Embassy listening on ${PORT}`));
